# ----------------------------------------------------------------------
# Makefile
# ----------------------------------------------------------------------

all: clean
.PHONY: clean

clean:
	rm -f core *~ *.stackdump
	rm -f students.dat contact.txt raindata.dat
	find . -name "*.err" -exec rm -f {} \;
	find . -name "*.lst" -exec rm -f {} \;
	find . -name "*.pex" -exec rm -f {} \;
	find . -name "*.o1" -exec rm -f {} \;
	find . -name "*.o" -exec rm -f {} \;
	find . -name "*.d" -exec rm -f {} \;
