# ----------------------------------------------------------------------
# Makefile
# ----------------------------------------------------------------------

all: clean
.PHONY: clean

clean:
	rm -f core *~ *.stackdump
	rm -f students.dat contact.txt raindata.dat
	rm -f src/*.err units/*.err
	rm -f src/*.lst units/*.lst
	rm -f src/*.pex units/*.pex
	rm -f src/*.o1 units/*.o1
	rm -f src/*.o units/*.o
	rm -f src/*.d units/*.d
